version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
      - "9229:9229" # Optional: Debugging port for Node.js
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      PORT: 5000
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run server:dev # Ensure this script uses nodemon

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start # Runs the React development server

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
  node_modules_backend:
    driver: local
  node_modules_frontend:
    driver: local

networks:
  devnetwork:
    driver: bridge